spring:
        datasource:
                url: jdbc:postgresql://localhost:5433/tienda_compensar
                username: postgres
                password: CR7elmejor*
                driver-class-name: org.postgresql.Driver
        jpa:
                hibernate:
                        ddl-auto: update
                        show-sql: true
                properties:
                        format_sql: true
                database: postgresql
                database-platform: org.hibernate.dialect.PostgreSQLDialect